[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"
evm_version = "shanghai"
via_ir = true
optimizer_runs = 1_000_000

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@euler-interfaces/=lib/euler-interfaces/interfaces/1/",
    "@createx-forge/=lib/createx-forge/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
